# Generated by Django 4.2.6 on 2024-01-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_vote_vote_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to='profile_pics/'),
        ),
    ]
